app/models/conteudo.py
from config import db

class Trabalho(db.Model):
    __tablename__ = "trabalhos"

    id = db.Column(db.Integer, primary_key=True, nullable=False, unique=True)
    titulo = db.Column(db.String(200), nullable=False)
    descricao = db.Column(db.Text, nullable=False)
    link = db.Column(db.String(300), nullable=True)  # Opcional

    def __init__(self, titulo, descricao, link=None):
        self.titulo = titulo
        self.descricao = descricao
        self.link = link

    def __repr__(self):
        return f'<Trabalho {self.titulo}>'

app/models/mensagens.py
from config import db
from flask_login import UserMixin

class Mensagens(db.Model, UserMixin):
    __tablename__ = "mensagens"
    id = db.Column(db.Integer, primary_key=True, nullable=False, unique=True)
    mensagem = db.Column(db.String(500), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', name='fk_mensagens_user_id'), nullable=True)  # Definir um nome para a restrição de chave estrangeira
    user = db.relationship('User', backref=db.backref('mensagens', lazy=True))

    def __init__(self, mensagem=None, user_id=None):
        self.mensagem = mensagem
        self.user_id = user_id
    
    def __repr__(self):
        return f'<Mensagens {self.mensagem}>'

app/models/usuario.py
from config import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
   __tablename__="users"
   id = db.Column(db.Integer, primary_key=True, nullable=False, unique=True)
   name = db.Column(db.String(100), nullable=False)
   email = db.Column(db.String(100), nullable=False, unique=True, name='email')
   senha = db.Column(db.String(100), nullable=False)
   is_admin = db.Column(db.Boolean, default=False)
   
   def __init__(self, name, email, senha, is_admin=False):
    self.name = name
    self.email = email
    self.senha = senha
    self.is_admin = is_admin
   def __repr__(self):
     return f'<User {self.name}>'
   
   def as_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'email': self.email,
            'is_admin': self.is_admin
        }

app/__init__.py
from flask import Flask, render_template, request, redirect, url_for
from config import db
from config import lm
from flask_migrate import Migrate
from app.models.usuario import User
from flask_login import login_required, current_user
from app.controllers.user import user_bp
import os

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', 'ada')
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    db.init_app(app)
    lm.init_app(app)
    lm.login_view = 'user.login'
    lm.login_message = "Por favor, faça login para acessar esta página."
    lm.login_message_category = "info"
    migrate = Migrate(app, db)
    migrate.init_app(app, db)

    app.register_blueprint(user_bp, url_prefix='/user')

    @lm.user_loader
    def load_user(id):
        return User.query.get(id)

    @app.route('/')
    def index():
        return render_template('index.html')

    @app.route('/conheca')
    def conheca():
        return render_template('conheca.html')

    @app.route('/lovelace')
    def lovelace():
        return render_template('lovelace.html')

    @app.route('/dados')
    def dados():
        return render_template('dados.html')
    
    @app.route('/form_adm')
    def form_adm():
        return render_template('formulario_adm.html')
        
    @app.route('/cadastro')
    def cadastro():
        return render_template("cadastro.html")

    with app.app_context():
        db.create_all()

    return app

app/controllers/user.py
from flask import Blueprint, request, render_template, flash, redirect, jsonify, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from app.models.usuario import User
from app.models.mensagens import Mensagens
from app.models.conteudo import Trabalho
from flask_login import login_user, logout_user, login_required, current_user
from config import db  # Aqui estamos importando o db
from sqlalchemy.orm import joinedload
import os
from werkzeug.utils import secure_filename

user_bp = Blueprint('user', __name__)
UPLOAD_FOLDER = os.path.join('static', 'uploads')
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@user_bp.route('/upload', methods=['POST'])
def upload_trabalho():
    titulo = request.form.get('titulo')
    descricao = request.form.get('descricao')
    link = request.form.get('link')  # Pode ser None
    # Salva os dados no banco de dados
    novo_trabalho = Trabalho(
        titulo=titulo,
        descricao=descricao,
        link=link
    )
    db.session.add(novo_trabalho)
    db.session.commit()
    return redirect(url_for('user.nossos_trabalhos'))

@user_bp.route('/trabalho/<int:trabalho_id>/delete', methods=['POST'])
@login_required
def delete_trabalho(trabalho_id):
    trabalho = Trabalho.query.get_or_404(trabalho_id)
    
    # Verifica se o usuário é um administrador
    if current_user.is_admin:
        db.session.delete(trabalho)
        db.session.commit()
    
    return redirect(url_for('user.nossos_trabalhos'))

@user_bp.route('/nossos_trabalhos')
def nossos_trabalhos():
    trabalhos = Trabalho.query.all() 
    return render_template('nossos_trabalhos.html', trabalhos=trabalhos)
  
@user_bp.route('/user')
def usuarios():
    usuarios = User.query.all()  # Alterado de 'user' para 'User'
    return jsonify([usuario.as_dict() for usuario in usuarios])

@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    return render_template('login.html')

@user_bp.route('/usuario', methods=['GET', 'POST'])
def usuario():
    if request.method == 'POST':
        data = request.form

        if User.query.filter_by(email=data['email']).first():
            return redirect(url_for('user.login'))

        hashed_password = generate_password_hash(data['senha_login'])
        is_admin = data.get('is_admin') == 'on'
        new_user = User(name=data['usuario_login'], email=data['email'], senha=hashed_password, is_admin=is_admin)
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        return redirect(url_for('user.login'))  
    else: 
        return redirect(url_for('user.cadastro'))  

@user_bp.route('/conectar', methods=['GET', 'POST'])
def conectar():
    if request.method == 'POST':
        
        user = User.query.filter_by(email=request.form['email']).first()
        
        if user and check_password_hash(user.senha, request.form['senha']):
            login_user(user, remember=True)
            return render_template('rede_de_apoio.html')   
        else:
            flash('Email ou senha incorretos', 'danger')
            return redirect(url_for('user.login')) 


@user_bp.route('/logoff')
def logoff():
	logout_user()
	return redirect('/')

@user_bp.route('/delete_user', methods=['POST'])
@login_required
def delete_user():
    user_to_delete = User.query.get(current_user.id)  # Pega o usuário logado, ou use outro ID se for admin

    if user_to_delete:
        try:
            db.session.delete(user_to_delete)  # Remove o usuário
            db.session.commit()  # Salva as mudanças no banco de dados
            flash('Usuário deletado com sucesso!', 'success')
        except Exception as e:
            db.session.rollback()
            flash(f'Ocorreu um erro ao tentar deletar o usuário: {str(e)}', 'error')

    return redirect(url_for('user.logoff'))  

@user_bp.route('/rede_apoio')
@login_required
def rede_apoio():
    mensagens = Mensagens.query.options(joinedload(Mensagens.user)).all()
    return render_template('rede_de_apoio.html', mensagens=mensagens)


@user_bp.route('/mensagens', methods=['POST'])
def mensagens():
    if request.method == 'POST':
        data = request.form
        nova_mensagem = Mensagens(mensagem=data['mensagens'], user_id=current_user.id)  # Associa a mensagem ao usuário logado
        db.session.add(nova_mensagem)
        db.session.commit()
    return redirect(url_for('user.rede_apoio'))

@user_bp.route('/mensagem/<int:mensagem_id>/delete', methods=['POST'])
@login_required
def delete_mensagem(mensagem_id):
    mensagem = Mensagens.query.get(mensagem_id)  # Encontra a mensagem pelo ID

    # Verifica se a mensagem existe e se o usuário logado é o proprietário
    if mensagem and mensagem.user_id == current_user.id:
        try:
            db.session.delete(mensagem)  # Apaga a mensagem
            db.session.commit()  # Confirma as alterações no banco
        except Exception as e:
            db.session.rollback()
            flash(f'Ocorreu um erro ao tentar excluir a mensagem: {str(e)}', 'error')
    else:
        flash('Você não tem permissão para excluir esta mensagem.', 'error')

    return redirect(url_for('user.rede_apoio')) 
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,  shrink-to-fit=no">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <link rel="icon" href="/static/img/FaviconADA.png" type="image/png">


    <title>Projeto Ada</title>
    <style>
        {% block extra_css %}{% endblock %}
    </style>
</head>

<body>
    <header>
        <div class="logo_ada">
            <a href="{{url_for('index')}}"><img src="/static/img/logo_ada.png" alt=""></a>
        </div>

        <nav class="navbar">
            <ul>
                <li><a href="{{url_for('conheca')}}">Conheça-nos</a></li>
                <li><a href="{{url_for('user.nossos_trabalhos')}}">Nossos Trabalhos</a></li>
                <li><a href="{{url_for('lovelace')}}">Lovelace</a></li>
                <li><a href="{{url_for('dados')}}">Dados</a></li>
            </ul>
        </nav>

        <div class="rede_de_apoio">
            <a href="{{url_for('user.rede_apoio')}}">Rede de apoio</a>
        </div>
    </header>
    
    <main>
        {% block conteudo %}
        {% endblock %}
    </main>
    
    <footer>
        <div class="footer-container">
            <a href="https://www.instagram.com/ada.ifzn?igsh=ZDNxOGV5aW5oajlh"> <img src="/static/img/logoinsta.png" alt="Nosso instagram" class="logo-esquerda"></a>
            <img src="/static/img/Lovelace.svg" alt="Lovelace" class="logolovelace">
            <img src="/static/img/IFlovelace.svg" alt="IFRN" class="logo-direita">
        </div>
    </footer>
</body>

</html>

app/templates/cadastro.html
{% extends 'base.html' %}
{% block extra_css %}
    .navbar, .rede_de_apoio, .logo-esquerda{
        display: none !important;
    }
    .footer-container {
        justify-content: end;
    }
{% endblock %}

    {% block conteudo %}   
    <div class='conteinerform_cadastro'>
        <form class="cadastro_form" action="{{url_for('user.usuario')}}" method="post">
            <h1 class="cadastro_titulo_form">Faça seu Cadastro</h1>
    
            <div class="conteiner_inputs_cadastro">
                <label for="">Usuário:</label>
                <input placeholder="nome do usuario" type="text" name="usuario_login"><br/>
    
                <label>Email:</label>
                <input placeholder="Email" type="email" name="email"><br/>

                <label>Senha:</label>
                <input placeholder="Senha" type="password" name="senha_login"><br/>
            </div>

            <div class="admcheck"> 
                <input type="checkbox" id="is_admin" name="is_admin"/>
                <label for="is_admin">Administrador</label>
            </div>

            <div>
                <button class="cadastro_botao" type="submit">Enviar</button>
            </div>
        </form>
    </div>
    {%endblock%}

app/templates/conheca.html
{% extends 'base.html' %}

    {% block conteudo %}
    <section class="titulogeral">
            <h1 class="titulo">Conheça nossa equipe</h1>
            <p class="subtitulo">Pessoas que buscam fazer a diferença por meio do projeto Ada</p>
    </section>
    <section class="cards_equipe">
        <div class="container_equipe">
            <div class="card">
                <img src="/static/img/alba.jpeg" alt="">
                <h4>Alba Lopes</h4>
                <p>Professora IFRN</p>
            </div>
            <div class="card">
                <img src="/static/img/fotokarol.png" alt="">
                <h4>Karolayne Azevedo</h4>
                <p>Membro externo</p>
            </div>
            <div class="card">
                <img src="/static/img/fotoclara.png" alt="">
                <h4>Clara Freire</h4>
                <p>Aluna 3º de Informática para Internet</p>
            </div>
            <div class="card">
                <img src="/static/img/fotolaura.png" alt="">
                <h4>Maria Laura</h4>
                <p>Aluna 3º de Informática para Internet</p>
            </div>
        </div>
    </section>

    <section class="container-geral-sobre-o-ada">
        <section class="container_sobre_o_ada">
            <h2>Sobre o Projeto Ada</h2>
            <div class="textos_sobre_o_ada">
                <p>Estudos apontam que meninas se interessam menos pelas áreas STEM (do inglês, Science, Technology, Engineering, and Mathematics), não por incapacidade cognitiva, mas por questões políticas, pela falta de estrutura educacional, social, cultural e principalmente devido a estereótipos. Dados indicam que as mulheres representam apenas 28% da força de trabalho nessas áreas [PNUD 2023]. A partir disso, a baixa representatividade feminina torna-se um fator preocupante, visto o que é apontado por [Lima 2013], de que as mulheres são consideradas um fator chave para ampliar o interesse das novas gerações pelas áreas STEM, tendo em vista do seu poder de influência em diversos setores da sociedade e diversas gerações.</p>

                <p>Com base na disparidade de gênero nas áreas, tanto no cenário local quanto global, e na inquietação de alunas e professoras surge o Projeto Ada, um projeto de extensão que visa estudar e promover a participação feminina nas áreas STEM. As atividades realizadas incluem pesquisas bibliográficas e análise de dados referentes à participação feminina, assim como rodas de conversas, exibições de filmes temáticos e oficinas de desenvolvimento de jogos digitais com o objetivo de conscientizar sobre a baixa representatividade das mulheres e fomentar o interesse das mesmas por essas áreas.
                </p>
            </div>
        </section>
    </section>
    

    <section>
        <h1 class="titulo_conheca_pt2">Depoimentos</h1>
    </section>
    <section>
        <div class="container_depoimentos">
            <div class="card_dp">
                <h4>Alba Lopes:</h4>
                <p>“Fala muito impactante de Alba”</p>
            </div>
            <div class="card_dp">
                <h4>Karolyne Azevedo:</h4>
                <p>“Fala muito impactante de Karol”</p>
            </div>
            <div class="card_dp">
                <h4>Clara Freire:</h4>
                <p>“Fala muito impactante de Clara”</p>
            </div>
            <div class="card_dp">
                <h4>Maria Laura:</h4>
                <p>“Fala muito impactante de Laura”</p>
            </div>
        </div>
    </section>
    {%endblock%}

app/templates/dados.html
{% extends 'base.html' %}

    {% block conteudo %}
    <section class="titulogeral">
        <h1 class="titulo">Dados e Estatísticas</h1>
        <p class="subtitulo">Confira abaixo alguns dos resultados do Projeto Ada</p>
    </section>







{%endblock%}

app/templates/formulario_adm.html
{% extends 'base.html' %}

    {% block conteudo %}
    <section class="titulogeral">
        <h1 class="titulo">Adicione conteúdo aqui</h1>
        <p class="subtitulo">Conteúdo referente a página de nossos trabalhos</p>
    </section>

    <section>
        <div class='conteinerform_adm'>
            <form class="adm_form" action="{{url_for('user.upload_trabalho')}}" method="POST" enctype="multipart/form-data">
                <h1 class="adm_titulo_form">Envie um trabalho</h1>
        
                <div class="conteiner_inputs_adm">
                    <label for="">Adicione um título aqui:</label>
                    <input placeholder="Título" type="text" name="titulo"><br/>
        
                    <label for="">Adicione uma descrição aqui:</label>
                    <input placeholder="Descrição" type="text" name="descricao"><br/>
                    
                    <label for="link">Insira um link:</label>
                    <input type="url" name="link" id="link" placeholder="https://exemplo.com">
                </div>
                <div>
                    <button class="adm_botao" type="submit">Enviar</button>
                </div>
            </form>
        </div>

    </section>


    
    {%endblock%}

app/templates/index.html
{% extends 'base.html' %}

    {% block conteudo %}
    <body class="paginaindex">
        <div>
            <div class="backgroundindex"></div>
            <section class="texto_index">
                <h1>Junte-se e conheça o <br>projeto <img src="/static/img/Ada.png" alt=""></h1>
                <h2>O que somos?</h2>
                <p>Nós do projeto Ada buscamos <br> ajudar e apoiar mulheres que <br> desejem ingressar ou se <br> aperfeiçoar nas áreas STEM, sendo <br> por meio de Sites, documentos, <br> interações interpessoais e <br> materiais de estudo.</p>
            </section>
        </div>    
    </body>    
    {%endblock%}

app/templates/login.html
{% extends 'base.html' %}
{% block extra_css %}
    .navbar, .rede_de_apoio, .logo-esquerda{
        display: none !important;
    }
    .footer-container {
        justify-content: end;
    }
{% endblock %}

{% block conteudo %}

{% set mensagens = get_flashed_messages(with_categories=true) %} 


<body>
    <div class='conteinerform'>
        <form class="form" action="{{url_for('user.conectar')}}" method="post">
            <h1 class="titulo_form">Faça seu Login</h1>
                <div class="conteiner_inputs">
                    <label for="">Email:</label>
                    <input placeholder="Exemplo@email.com" type="email" name="email"><br/>
                    <label>Senha:</label>
                    <input placeholder="Senha" type="password" name="senha"><br/>
                </div>
                <div>
                    <button class="botao" type="submit">Entrar</button>
                </div>
                <div class="facacadastro">
                    <p>Não tem conta? <a href="{{url_for('cadastro')}}">Faça seu cadastro</a></p>
                </div>

            {% if mensagens %}
            {% for categoria, msg in mensagens %}
                <div class="senha_incorreta">
                    {{ msg }}
                </div>
            {% endfor %}
            {% endif %}

        </form>
    </div>
</body>


{%endblock%}

app/templates/lovelace.html
{% extends 'base.html' %}

    {% block conteudo %}
        <section class="titulogeral">
            <img class="titulo" src="/static/img/Lovelace (1).png" alt="">
            <p class="subtitulo">Conheça mais sobre mulheres importantes em áreas STEM</p>
        </section>
        
        <section class="container-ada">
            <div class="div-esquerda-ada">
                <h2>Quem foi Ada Lovelace?</h2>
                <p>Ada Lovelace foi uma matemática e escritora inglesa, considerada a primeira programadora de computador. No século XIX, ela criou o primeiro algoritmo para uma máquina, a máquina analítica de Charles Babbage, e antecipou o potencial das máquinas para além dos cálculos, vislumbrando seu uso em áreas como música e texto. Seu trabalho é fundamental para a história da computação e também serve de inspiração para mulheres que desejam seguir carreiras na área de STEM.</p>
            </div>
            <div class="div-direita-ada">
                <img src="static/img/Mask group.png" alt="">
            </div>
        </section>

        <div class="container-o1">
            <div class="container-outrasmulheres">
                <h2 class="titulo-outras">Outras mulheres</h2>
                <p class="subtitulo-outras">Que foram de extrema importância para a área STEM</p>

                <div class="cards-geral-outras">
                    <div class="cards-outras">
                        <div class="div-direita-outras">
                            <img src="/static/img/Ellipse 31.png" alt="">
                            <h2>Marie Curie (1867–1934)</h2>
                        </div>
                        <div class="div-esquerda-outras">
                            <p>Pioneira em radioatividade, foi a primeira pessoa a ganhar dois prêmios Nobel em áreas diferentes.</p>
                        </div>
                    </div>
                
                    <div class="cards-outras">
                        <div class="div-direita-outras">
                            <img src="/static/img/Ellipse 32.png" alt="">
                            <h2>Katherine Johnson (1918–2020)</h2>
                        </div>
                        <div class="div-esquerda-outras">
                            <p>Matemática da NASA, seus cálculos foram essenciais para as missões Apollo.</p>
                        </div>
                    </div>
                
                    <div class="cards-outras">
                        <div class="div-direita-outras">
                            <img src="/static/img/Ellipse 32 (1).png" alt="">
                            <h2>Rosalind Franklin (1920–1958)</h2>
                        </div>
                        <div class="div-esquerda-outras">
                            <p>Colaborou para a descoberta da estrutura do DNA com suas fotografias de raios-X.</p>
                        </div>
                    </div>
                
                    <div class="cards-outras">
                        <div class="div-direita-outras">
                            <img src="/static/img/Ellipse 32 (2).png" alt="">
                            <h2>Hedy Lamarr (1914–2000)</h2>
                        </div>
                        <div class="div-esquerda-outras">
                            <p>Inventora do sistema que deu origem ao Wi-Fi e Bluetooth.</p>
                        </div>
                    </div>
                </div>                
            </div>
        </div>


        
    {%endblock%}

app/templates/nossos_trabalhos.html
{% extends 'base.html' %}

    {% block conteudo %}
    <section class="titulogeral">
        <h1 class="titulo">Nossos Trabalhos</h1>
        <p class="subtitulo">Conheça abaixo alguns de nossos trabalhos</p>
    </section>
    
    <div class="banner">
        <div class="texto-banner">
            <p>O projeto ADA já atuou em diversas escolas por Natal, mudando e conscientizando a vida de diversas mulheres por onde passa.</p>
        </div>
        <div class="img-banner">
            <img src="/static/img/7 2.png" alt="">
        </div>
    </div>
    

    <div class="materiais-apresentados">
        <div class="titulo-container">
            <h1 class="titulo_materiaisAP">Trabalhos Apresentados</h1>
        </div>
        
        <div class="container-cards">
            {% for trabalho in trabalhos %}
            <div class="cardnt">
                <h2>{{ trabalho.titulo }}</h2>
                <p>{{ trabalho.descricao }}</p>
                {% if trabalho.link %}
                    <a href="{{ trabalho.link }}" target="_blank">Veja mais</a>
                {% endif %}
                {% if current_user.is_admin %}
                    <form action="{{ url_for('user.delete_trabalho', trabalho_id=trabalho.id) }}" method="post">
                        <button type="submit" onclick="return confirm('Tem certeza que deseja excluir este trabalho?')">Excluir</button>
                    </form>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    
        <div class="navegacao">
            <img class="seta" src="/static/img/seta_esquerda.png" alt="Seta Esquerda">
            <img class="seta" src="/static/img/seta_direita.png" alt="Seta Direita">
        </div>
    </div>

    
    
    
    
    {%endblock%}

app/templates/rede_de_apoio.html
{% extends 'base.html' %}

{% block conteudo %}
<section class="pag_rede_apoio">
    
    <aside class="sidebar_rda">
        <div>
            <div class="perfil_usuario">
                <p class="nome_usuario">{{current_user.name}}</p>
                {% if current_user.is_admin %}
                    <p class="cargo_usuario">Administrador</p>
                {% endif %}
            </div>

            <div class="dados_pessoais">
                <h3>Dados Pessoais</h3>
                <p class="info_pessoal">{{ current_user.email }}</p>
                <p class="info_pessoal">Mensagens enviadas: {{ current_user.message_count }}</p>
                
                {% if current_user.is_authenticated and current_user.is_admin %}
                <a href="{{ url_for('form_adm') }}" class="botao_submeter">Submeter projeto</a>
                {% endif %}
            </div>
            
            <div class="botoes_sair_deletar">
                <form action="{{ url_for('user.delete_user') }}" method="post">
                    <button type="submit" class="botao_deletar" onclick="return confirm('Tem certeza que deseja excluir sua conta?')">
                        Deletar Conta
                    </button>
                </form>
                <a class="nav-link" href="{{ url_for('user.logoff') }}">Sair da Conta</a>
            </div>
        </div>
    </aside>

    <section>
        <div class="titulogeral">
            <h1 class="titulo">Rede de Apoio</h1>
            <p class="subtitulo">Compartilhe sua experiência na área STEM e incentive outras mulheres.</p>
        </div>

        <div class="containerrda">
            <div class="formrededeapoio">
                <form action="{{ url_for('user.mensagens') }}" method="post">
                    <div>
                        <input class="textboxinput" type="text" id="mensagens" name="mensagens" placeholder="Fale conosco"><br>
                    </div>
                    <div>
                        <button class="botaorede" type="submit">Enviar</button>
                    </div>
                </form>
            </div>
        
            <ul class="messagecard">
                {% for i in mensagens %}
                    <li class="cardrede">
                        <div class="cardcontent">
                            <div class="avatar"></div> <!-- Avatar aqui -->
                            <h4 class="cardusername">{{ i.user.name if i.user and i.user.name else 'Usuário desconhecido' }}:</h4>
                            <p class="cardusertext">{{ i.mensagem }}</p>
                            {% if i.user_id == current_user.id %}
                            <!-- Formulário para excluir mensagem -->
                                <form action="{{ url_for('user.delete_mensagem', mensagem_id=i.id) }}" method="post">
                                    <button type="submit" onclick="return confirm('Tem certeza que deseja excluir esta mensagem?')">Excluir</button>
                                </form>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

templates/cadastro.html
{% extends 'base.html' %}

    {% block conteudo %}   
    <div class='cadastro_form_geral'>
        <form class="cadastro_form" action="{{url_for('login')}}" method="post">
            <h1 class="cadastro_titulo_form">Faça seu Cadastro</h1>
    
            <div class="cadastro_fonte_form">
                <label for="">Usuário:</label>
                <input class="cadastro_input" placeholder="Nome de Usuário" type="text" name="usuario_login"><br/>
    
                <label for="">Email:</label>
                <input class="cadastro_input" placeholder="seuemail@exemplo.com" type="email" name="email"><br/>
    
                <label>Senha:</label>
                <input class="cadastro_input" placeholder="Senha" type="password" name="senha_login"><br/>
    
                <button class="cadastro_botao" type="submit">Enviar</button>
            </div>
        </form>
    </div>
    {%endblock%}

templates/login.html
{% extends 'base.html' %}

{% block conteudo %}
{% set mensagens = get_flashed_messages(with_categories=true) %} 
{% if mensagens %}     
{% for categoria, msg in mensagens %}
    <div class="senha_incorreta">
        {{ msg }}
    </div>
{% endfor %}
{% endif %}
<body class="bodylogincadastro">
    <div class='form_geral'>
        <form class="form" action="{{url_for('rede_de_apoio')}}" method="post">
            <h1 class="titulo_form">Faça seu Login</h1>
    
            <div class="fonte_form">
                <label for="">Usuário:</label><br/>
                <input placeholder="exemplo@email.com" type="text" name="usuario"><br/>
    
                <label>Senha:</label><br/>
                <input placeholder="senha123" type="password" name="senha"><br/>
    
                <button class="botao" type="submit">Entrar</button>
                <p>Não tem conta? <a href="{{url_for('cadastro')}}">Faça seu cadastro</a></p>
            </div>
        </form>
    </div>
</body>
{%endblock%}